version: '3'

services:
  # The reverse proxy service (Traefik)
  traefik:
    image: traefik:v2.5  # The official Traefik docker image
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 8081:80      # The HTTP port
      - 8083:443      # The HTTPS port
      - 8080:8080  # The Web UI (enabled by --api)
    volumes:
      - $PWD/conf/traefik.yml:/etc/traefik/traefik.yml
      - $PWD/logs/traefik.log:/var/log/traefik/traefik.log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # A container that exposes a simple API
  whoami:
    image: emilevauge/whoami  # A container that exposes an API to show its IP address
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"


  http-provider:
    image: httpd:2.4
    volumes:
      - $PWD/http-provider/dynamic_conf:/usr/local/apache2/htdocs/dynamic_conf
      - $PWD/opa:/usr/local/apache2/htdocs/opa
    ports:
      - 8070:80
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"

  opa:
    image: openpolicyagent/opa:0.30.1
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
